// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: follow_feed.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFollowFeeds = `-- name: CreateFollowFeeds :one

insert into follow_feed(id, created_at, updated_at, user_id,feed_id)
values($1, $2, $3, $4, $5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFollowFeedsParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFollowFeeds(ctx context.Context, arg CreateFollowFeedsParams) (FollowFeed, error) {
	row := q.db.QueryRowContext(ctx, createFollowFeeds,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FollowFeed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const deleteFollowFeedForUser = `-- name: DeleteFollowFeedForUser :exec
delete 
from follow_feed
where id=$1 AND user_id=$2
`

type DeleteFollowFeedForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFollowFeedForUser(ctx context.Context, arg DeleteFollowFeedForUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollowFeedForUser, arg.ID, arg.UserID)
	return err
}

const getFeedsForUser = `-- name: GetFeedsForUser :many

select id, created_at, updated_at, user_id, feed_id
from follow_feed
where user_id = $1
`

func (q *Queries) GetFeedsForUser(ctx context.Context, userID uuid.UUID) ([]FollowFeed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FollowFeed
	for rows.Next() {
		var i FollowFeed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
